### ISSUE TITLE
MDMs cannot have a field named Version.

### ISSUE THREAD

**Issue by jasondavis11** [afrl-rq/LmcpGen#18]
The C# implementation generates an instance property named Version that causes a conflict. Suggest renaming the always-generated property to SeriesVersion instead of simply Version. Alternatively (or perhaps additionally), update LmcpGen to report an error if an MDM contains any field name that will conflict with properties/methods that the various languages will generate.

**Comment by derekkingston** [comment]
I'll make the change on the C# version to change that property name. Since LmcpGen outputs for a number of languages, keywords from every language need to be avoided (in particular, message and field names in the MDM can cause problems). I'll keep this issue open until a complete keyword list is created and added to the documentation.

**Comment by derekkingston** [comment]
This looks to be a problem with the CMASI MDM that includes the message KeyValuePair which has the field names 'Key' and 'Value'. This issue will stay open until a check is added to LmcpGen to check for keywords and report conflicts.

**Comment by derekkingston** [comment]
The particular issue regarding use of 'Version' should be fixed. As suggested, it is renamed 'SeriesVersion'
